version: "3.5"
services:
  caddy:
    build: ./.config/caddy
    image: caddy:2.4.6-alpine
    depends_on:
      - php
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./.kube:/root/.kube
    ports:
      - 80:80
      - 443:443

  php:
    build: .
    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/

  mariadb:
    image: mariadb:10.7
    environment:
      - MYSQL_ROOT_PASSWORD=cscloud
      - MYSQL_DATABASE=cscloud
      - MYSQL_USER=cscloud
      - MYSQL_PASSWORD=cscloud
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306

volumes:
  caddy_data:
  caddy_config:
  mariadb:
